name: Auditd Syntax Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Add this block to enable manual triggering
    inputs:
      reason:
        description: 'Reason for running the workflow'
        required: true
        default: 'Manual run'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update package information
        run: sudo apt update

      - name: Install auditd
        run: sudo apt install -y auditd

      - name: Start auditd
        run: if ! (systemctl is-active auditd); then sudo systemctl start auditd; fi

      - name: Remove default rules
        run: |
          sudo ls -l /etc/audit/rules.d/
          sudo rm /etc/audit/audit.rules
          sudo rm -rf /etc/audit/rules.d
          sudo mkdir /etc/audit/rules.d

      - name: Copy rules file to rules directory
        run: sudo cp $GITHUB_WORKSPACE/audit.rules /etc/audit/rules.d/

      - name: Check rules
        run: sudo augenrules --check 2>&1

      - name: Load rules
        run: |
          sudo augenrules --load 2>&1
          sudo wc -l /etc/audit/rules.d/audit.rules
          sudo auditctl -l

      - name: Make some test shell comands
        run: |
          logger test
          echo "This is a test" > /tmp/test.txt
          cat /tmp/test.txt
          echo "$(</tmp/test.txt)"
          sudo echo "$(</var/log/audit/audit.log)" 
  
          python3 auditd_json_converter.py -o /tmp/auditd2.json -v     
          echo "$(</tmp/auditd2.json)"

      - name: Build and convert audit.log and check output 
        run: |
          python3 auditd_json_converter.py -f ./test/audit.log -o /tmp/auditd.json -v     
          echo "$(</tmp/auditd.json)"

          expected='[
          {
              "type": "EXECVE",
              "timestamp": "2018-07-25 03:25:08",
              "argc": "2",
              "a0": "cat",
              "a1": "10-procmon.rules"
          },
          {
              "type": "EXECVE",
              "timestamp": "2018-07-25 03:25:09",
              "argc": "4",
              "a0": "grep",
              "a2": "procmon",
              "a3": "/var/log/audit/audit.log"
          }
          ]'

          echo "$expected" > /tmp/expected.json
          # diff -q /tmp/expected.json /tmp/audit.json